up:
	python3 ./app.py

test:
	curl -X POST 'http://127.0.0.1:5555/api' -H 'Content-Type: application/json' -d @test_data.json

test_server:
	curl -X POST 'http://188.225.36.185/api' -H 'Content-Type: application/json' -d @test_data.json
